### ISSUE TITLE
Fix `bitFlip` def

### ISSUE THREAD

**Issue by honoki** [kelalaka153/CBC-Bit-Flipping-Attack#1]
In python3, the `bitFlip` def seems to be broken - this is a working version:

```python
def bitFlip( pos, bit, data):
    raw = b64decode(data)
    list1 = list(raw)
    list1[pos] = list1[pos] ^ bit
    raw = bytes(list1)
    return b64encode(bytes(raw))
```

**Comment by kelalaka153** [comment]
Yes, you are right. I've tested and updated with your version. Thanks.

**Comment by kelalaka153** [comment]
Issue is solved with honoki's contribution.

**Comment by kelalaka153** [comment]
Issue is solved with honoki's contribution.
